import React, { createContext, useContext, useState } from 'react';

export type Language = 'zh-TW' | 'en-US' | 'zh-CN' | 'vi-VN' | 'id-ID' | 'th-TH' | 'ja-JP' | 'ko-KR' | 'es-ES' | 'fr-FR' | 'de-DE' | 'pt-BR' | 'ru-RU' | 'ar-SA';

const translations: Record<Language, Record<string, string>> = {
  'zh-TW': {
    adminTitle: '工地表單自動化管理後台',
    uploadTemplate: '上傳 Excel 樣板',
    dropHere: '拖曳至此或點擊選擇 Excel (.xlsx) 樣板',
    fieldDetails: '具名範圍欄位對應與解析',
    fieldName: '具名範圍 (Named Range)',
    fieldType: '欄位類型',
    aspectRatio: '裁剪長寬比',
    resolution: '解析度要求',
    isRequired: '必填',
    previewApp: '模擬填寫端 App UI 渲染',
    exportJson: '匯出配置 JSON',
    typeText: '純文字 (Text)',
    typeImage: '工地相片 (Image)',
    loading: '解析 Excel 中...',
    saveSuccess: '設定已儲存！',
    emptyConfig: '請先上傳 Excel 樣板以解析欄位',
    inspectorLabel: '督導員名稱',
    dateLabel: '檢查日期',
  },
  'en-US': {
    adminTitle: 'Site Form Automation Admin Portal',
    uploadTemplate: 'Upload Excel Template',
    dropHere: 'Drag & drop or click to select Excel (.xlsx) template',
    fieldDetails: 'Named Ranges Column Mapping & Analytics',
    fieldName: 'Named Range',
    fieldType: 'Field Type',
    aspectRatio: 'Crop Aspect Ratio',
    resolution: 'Resolution Standard',
    isRequired: 'Required',
    previewApp: 'Simulated Client App Form UI',
    exportJson: 'Export Configuration JSON',
    typeText: 'Text Field',
    typeImage: 'Site Photo',
    loading: 'Parsing Excel...',
    saveSuccess: 'Configuration saved!',
    emptyConfig: 'Please upload an Excel template first',
    inspectorLabel: 'Inspector Name',
    dateLabel: 'Inspection Date',
  },
  'zh-CN': {
    adminTitle: '工地表单自动化管理后台',
    uploadTemplate: '上传 Excel 样板',
    dropHere: '拖拽至此或点击选择 Excel (.xlsx) 样板',
    fieldDetails: '具名范围栏位对应与解析',
    fieldName: '具名范围 (Named Range)',
    fieldType: '栏位类型',
    aspectRatio: '裁剪长宽比',
    resolution: '解析度要求',
    isRequired: '必填',
    previewApp: '模拟填写端 App UI 渲染',
    exportJson: '导出配置 JSON',
    typeText: '纯文字 (Text)',
    typeImage: '工地相片 (Image)',
    loading: '解析 Excel 中...',
    saveSuccess: '设定已储存！',
    emptyConfig: '请先上传 Excel 样板以解析栏位',
    inspectorLabel: '督导员名称',
    dateLabel: '检查日期',
  },
  'vi-VN': {
    adminTitle: 'Cổng Quản trị Tự động hóa Biểu mẫu Công trường',
    uploadTemplate: 'Tải lên Mẫu Excel',
    dropHere: 'Kéo thả hoặc nhấp để chọn mẫu Excel (.xlsx)',
    fieldDetails: 'Ánh xạ và Phân tích Cột Dải ô Đã đặt tên',
    fieldName: 'Dải ô Đã đặt tên (Named Range)',
    fieldType: 'Loại Trường',
    aspectRatio: 'Tỷ lệ Cắt',
    resolution: 'Tiêu chuẩn Độ phân giải',
    isRequired: 'Bắt buộc',
    previewApp: 'Mô phỏng Giao diện Điền Biểu mẫu App',
    exportJson: 'Xuất Cấu hình JSON',
    typeText: 'Trường Văn bản (Text)',
    typeImage: 'Ảnh Công trường (Image)',
    loading: 'Đang phân tích Excel...',
    saveSuccess: 'Đã lưu cấu hình!',
    emptyConfig: 'Vui lòng tải lên mẫu Excel trước',
    inspectorLabel: 'Tên thanh tra',
    dateLabel: 'Ngày kiểm tra',
  },
  'id-ID': {
    adminTitle: 'Portal Admin Otomatisasi Formulir Konstruksi',
    uploadTemplate: 'Unggah Templat Excel',
    dropHere: 'Seret & lepas atau klik untuk memilih templat Excel (.xlsx)',
    fieldDetails: 'Pemetaan Kolom & Analisis Rentang Bernama',
    fieldName: 'Rentang Bernama (Named Range)',
    fieldType: 'Tipe Kolom',
    aspectRatio: 'Rasio Potong',
    resolution: 'Standar Resolusi',
    isRequired: 'Wajib',
    previewApp: 'Simulasi UI Formulir Aplikasi Pengguna',
    exportJson: 'Ekspor Konfigurasi JSON',
    typeText: 'Kolom Teks (Text)',
    typeImage: 'Foto Lapangan (Image)',
    loading: 'Menganalisis Excel...',
    saveSuccess: 'Konfigurasi disimpan!',
    emptyConfig: 'Silakan unggah templat Excel terlebih dahulu',
    inspectorLabel: 'Nama Inspektur',
    dateLabel: 'Tanggal Inspeksi',
  },
  'th-TH': {
    adminTitle: 'ระบบการจัดการแบบฟอร์มไซต์งานอัตโนมัติ',
    uploadTemplate: 'อัปโหลดเทมเพลต Excel',
    dropHere: 'ลากและวาง หรือคลิกเพื่อเลือกเทมเพลต Excel (.xlsx)',
    fieldDetails: 'การแมปคอลัมน์และการวิเคราะห์ช่วงที่ตั้งชื่อ',
    fieldName: 'ช่วงที่ตั้งชื่อ (Named Range)',
    fieldType: 'ประเภทฟิลด์',
    aspectRatio: 'อัตราส่วนครอบตัด',
    resolution: 'มาตรฐานความละเอียด',
    isRequired: 'จำเป็น',
    previewApp: 'จำลองการแสดงผล UI บนแอปพลิเคชัน',
    exportJson: 'ส่งออกไฟล์กำหนดค่า JSON',
    typeText: 'ฟิลด์ข้อความ (Text)',
    typeImage: 'รูปถ่ายไซต์งาน (Image)',
    loading: 'กำลังวิเคราะห์ไฟล์ Excel...',
    saveSuccess: 'บันทึกการตั้งค่าแล้ว!',
    emptyConfig: 'กรุณาอัปโหลดเทมเพลต Excel ก่อน',
    inspectorLabel: 'ชื่อผู้ตรวจสอบ',
    dateLabel: 'วันที่ตรวจสอบ',
  },
  'ja-JP': {
    adminTitle: 'Site Form Automation Admin Portal',
    uploadTemplate: 'Upload Excel Template',
    dropHere: 'Drag & drop or click to select Excel (.xlsx) template',
    fieldDetails: 'Named Ranges Column Mapping & Analytics',
    fieldName: 'Named Range',
    fieldType: 'Field Type',
    aspectRatio: 'Crop Aspect Ratio',
    resolution: 'Resolution Standard',
    isRequired: 'Required',
    previewApp: 'Simulated Client App Form UI',
    exportJson: 'Export Configuration JSON',
    typeText: 'Text Field',
    typeImage: 'Site Photo',
    loading: 'Parsing Excel...',
    saveSuccess: 'Configuration saved!',
    emptyConfig: 'Please upload an Excel template first',
    inspectorLabel: 'Inspector Name',
    dateLabel: 'Inspection Date',
  },
  'ko-KR': {
    adminTitle: 'Site Form Automation Admin Portal',
    uploadTemplate: 'Upload Excel Template',
    dropHere: 'Drag & drop or click to select Excel (.xlsx) template',
    fieldDetails: 'Named Ranges Column Mapping & Analytics',
    fieldName: 'Named Range',
    fieldType: 'Field Type',
    aspectRatio: 'Crop Aspect Ratio',
    resolution: 'Resolution Standard',
    isRequired: 'Required',
    previewApp: 'Simulated Client App Form UI',
    exportJson: 'Export Configuration JSON',
    typeText: 'Text Field',
    typeImage: 'Site Photo',
    loading: 'Parsing Excel...',
    saveSuccess: 'Configuration saved!',
    emptyConfig: 'Please upload an Excel template first',
    inspectorLabel: 'Inspector Name',
    dateLabel: 'Inspection Date',
  },
  'es-ES': {
    adminTitle: 'Site Form Automation Admin Portal',
    uploadTemplate: 'Upload Excel Template',
    dropHere: 'Drag & drop or click to select Excel (.xlsx) template',
    fieldDetails: 'Named Ranges Column Mapping & Analytics',
    fieldName: 'Named Range',
    fieldType: 'Field Type',
    aspectRatio: 'Crop Aspect Ratio',
    resolution: 'Resolution Standard',
    isRequired: 'Required',
    previewApp: 'Simulated Client App Form UI',
    exportJson: 'Export Configuration JSON',
    typeText: 'Text Field',
    typeImage: 'Site Photo',
    loading: 'Parsing Excel...',
    saveSuccess: 'Configuration saved!',
    emptyConfig: 'Please upload an Excel template first',
    inspectorLabel: 'Inspector Name',
    dateLabel: 'Inspection Date',
  },
  'fr-FR': {
    adminTitle: 'Site Form Automation Admin Portal',
    uploadTemplate: 'Upload Excel Template',
    dropHere: 'Drag & drop or click to select Excel (.xlsx) template',
    fieldDetails: 'Named Ranges Column Mapping & Analytics',
    fieldName: 'Named Range',
    fieldType: 'Field Type',
    aspectRatio: 'Crop Aspect Ratio',
    resolution: 'Resolution Standard',
    isRequired: 'Required',
    previewApp: 'Simulated Client App Form UI',
    exportJson: 'Export Configuration JSON',
    typeText: 'Text Field',
    typeImage: 'Site Photo',
    loading: 'Parsing Excel...',
    saveSuccess: 'Configuration saved!',
    emptyConfig: 'Please upload an Excel template first',
    inspectorLabel: 'Inspector Name',
    dateLabel: 'Inspection Date',
  },
  'de-DE': {
    adminTitle: 'Site Form Automation Admin Portal',
    uploadTemplate: 'Upload Excel Template',
    dropHere: 'Drag & drop or click to select Excel (.xlsx) template',
    fieldDetails: 'Named Ranges Column Mapping & Analytics',
    fieldName: 'Named Range',
    fieldType: 'Field Type',
    aspectRatio: 'Crop Aspect Ratio',
    resolution: 'Resolution Standard',
    isRequired: 'Required',
    previewApp: 'Simulated Client App Form UI',
    exportJson: 'Export Configuration JSON',
    typeText: 'Text Field',
    typeImage: 'Site Photo',
    loading: 'Parsing Excel...',
    saveSuccess: 'Configuration saved!',
    emptyConfig: 'Please upload an Excel template first',
    inspectorLabel: 'Inspector Name',
    dateLabel: 'Inspection Date',
  },
  'pt-BR': {
    adminTitle: 'Site Form Automation Admin Portal',
    uploadTemplate: 'Upload Excel Template',
    dropHere: 'Drag & drop or click to select Excel (.xlsx) template',
    fieldDetails: 'Named Ranges Column Mapping & Analytics',
    fieldName: 'Named Range',
    fieldType: 'Field Type',
    aspectRatio: 'Crop Aspect Ratio',
    resolution: 'Resolution Standard',
    isRequired: 'Required',
    previewApp: 'Simulated Client App Form UI',
    exportJson: 'Export Configuration JSON',
    typeText: 'Text Field',
    typeImage: 'Site Photo',
    loading: 'Parsing Excel...',
    saveSuccess: 'Configuration saved!',
    emptyConfig: 'Please upload an Excel template first',
    inspectorLabel: 'Inspector Name',
    dateLabel: 'Inspection Date',
  },
  'ru-RU': {
    adminTitle: 'Site Form Automation Admin Portal',
    uploadTemplate: 'Upload Excel Template',
    dropHere: 'Drag & drop or click to select Excel (.xlsx) template',
    fieldDetails: 'Named Ranges Column Mapping & Analytics',
    fieldName: 'Named Range',
    fieldType: 'Field Type',
    aspectRatio: 'Crop Aspect Ratio',
    resolution: 'Resolution Standard',
    isRequired: 'Required',
    previewApp: 'Simulated Client App Form UI',
    exportJson: 'Export Configuration JSON',
    typeText: 'Text Field',
    typeImage: 'Site Photo',
    loading: 'Parsing Excel...',
    saveSuccess: 'Configuration saved!',
    emptyConfig: 'Please upload an Excel template first',
    inspectorLabel: 'Inspector Name',
    dateLabel: 'Inspection Date',
  },
  'ar-SA': {
    adminTitle: 'Site Form Automation Admin Portal',
    uploadTemplate: 'Upload Excel Template',
    dropHere: 'Drag & drop or click to select Excel (.xlsx) template',
    fieldDetails: 'Named Ranges Column Mapping & Analytics',
    fieldName: 'Named Range',
    fieldType: 'Field Type',
    aspectRatio: 'Crop Aspect Ratio',
    resolution: 'Resolution Standard',
    isRequired: 'Required',
    previewApp: 'Simulated Client App Form UI',
    exportJson: 'Export Configuration JSON',
    typeText: 'Text Field',
    typeImage: 'Site Photo',
    loading: 'Parsing Excel...',
    saveSuccess: 'Configuration saved!',
    emptyConfig: 'Please upload an Excel template first',
    inspectorLabel: 'Inspector Name',
    dateLabel: 'Inspection Date',
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh-TW');

  const t = (key: string): string => {
    return translations[language][key] || translations['zh-TW'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
